// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02j1P9sONKiXJXtZb4sXMUHiLzNno_JY',
    appId: '1:880570571188:web:09313280e5c48dcb2ffae1',
    messagingSenderId: '880570571188',
    projectId: 'flight-booking-app-a1d75',
    authDomain: 'flight-booking-app-a1d75.firebaseapp.com',
    storageBucket: 'flight-booking-app-a1d75.firebasestorage.app',
    measurementId: 'G-JYK086N5ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4J-6CrluX9Y3N-fsfr7iOfyM9Y3PS_EE',
    appId: '1:880570571188:android:13e75fbdf1c11e9d2ffae1',
    messagingSenderId: '880570571188',
    projectId: 'flight-booking-app-a1d75',
    storageBucket: 'flight-booking-app-a1d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHLSaqTgVD2zozyf1Mjx8W2etg4VY2tic',
    appId: '1:880570571188:ios:205677ca8933c1812ffae1',
    messagingSenderId: '880570571188',
    projectId: 'flight-booking-app-a1d75',
    storageBucket: 'flight-booking-app-a1d75.firebasestorage.app',
    androidClientId: '880570571188-jufbm3b3eic5i826t6khj9lojfcbbj0t.apps.googleusercontent.com',
    iosClientId: '880570571188-1fn4n60ndk8m3mt9c7ariutbququnvhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightClientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHLSaqTgVD2zozyf1Mjx8W2etg4VY2tic',
    appId: '1:880570571188:ios:205677ca8933c1812ffae1',
    messagingSenderId: '880570571188',
    projectId: 'flight-booking-app-a1d75',
    storageBucket: 'flight-booking-app-a1d75.firebasestorage.app',
    androidClientId: '880570571188-jufbm3b3eic5i826t6khj9lojfcbbj0t.apps.googleusercontent.com',
    iosClientId: '880570571188-1fn4n60ndk8m3mt9c7ariutbququnvhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightClientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA02j1P9sONKiXJXtZb4sXMUHiLzNno_JY',
    appId: '1:880570571188:web:0d8a77c32b9649b82ffae1',
    messagingSenderId: '880570571188',
    projectId: 'flight-booking-app-a1d75',
    authDomain: 'flight-booking-app-a1d75.firebaseapp.com',
    storageBucket: 'flight-booking-app-a1d75.firebasestorage.app',
    measurementId: 'G-GWX6NTV8LP',
  );
}
